// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa5364_vz6EMajnO7NcAFAz46O1cmTPKY',
    appId: '1:631306215122:web:a4ee2349cd23625e98570b',
    messagingSenderId: '631306215122',
    projectId: 'absensi-5bf62',
    authDomain: 'absensi-5bf62.firebaseapp.com',
    storageBucket: 'absensi-5bf62.firebasestorage.app',
    measurementId: 'G-R5DFJSDCNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0oQgEqAsk2fNY6T6LphQaXLHXdQ6ksss',
    appId: '1:631306215122:android:274d8c3954dd8ff598570b',
    messagingSenderId: '631306215122',
    projectId: 'absensi-5bf62',
    storageBucket: 'absensi-5bf62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQpRLgdqxBdFXVCOoN_hzqRvJnQu0MaFM',
    appId: '1:631306215122:ios:3e7c55aa1f7d605598570b',
    messagingSenderId: '631306215122',
    projectId: 'absensi-5bf62',
    storageBucket: 'absensi-5bf62.firebasestorage.app',
    iosBundleId: 'com.example.absensiKaryawan',
  );
}
